# Specifies a parent image
FROM golang:1.22.1-alpine3.18 

WORKDIR /app
COPY . /app

RUN go install -mod=mod github.com/githubnemo/CompileDaemon
RUN go mod download

EXPOSE 8080
# Specifies the executable command that runs when the container starts
# ENTRYPOINT CompileDaemon --build="go build main.go"

ENTRYPOINT CompileDaemon --build="go build ./cmd/main.go" --command=./main